#!/usr/bin/env bash
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Licensed under the Apache License, Version 2.0
#
# Author: Marco Massenzio (marco@alertavert.com)
#
set -eu
workdir=$(dirname $0)


version=$(grep -E '^package[[:blank:]]' ${workdir}/api/statemachine.proto |\
    sed -E 's/^package[[:blank:]]statemachine\.//' |\
    sed "s/[[:blank:]]*;//g" | sed 's/[[:blank:]]*$//')

echo "${version}"
