# Upon pushing to the release branch a new tag will be created
# in preparation for the release.
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)
#
name: Release Automation

on:
  push:
    branches:
      - release
env:
  AUTHOR: ${{ github.event.pusher.name }}
  EMAIL: ${{ github.event.pusher.email }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.19'
      - name: Install protoc-gen & build protos
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          make protos && make mod
          # TODO: remove debug echo
          find golang

      - name: Configure Git User
        run: |
          git config user.name "$AUTHOR"
          git config user.email "<$EMAIL>"

      - name: Generate commit tag
        run: |
          TAG=$(./get-tag)
          echo TAG=${TAG} >> $GITHUB_ENV

      - name: Commit generated code
        run:
          git add . && git commit -am "Protos updated to Rev. ${{ env.TAG }}" || true
          git push origin

      - name: Create release tag
        run: |
          git tag -fa golang/${{ env.TAG }} -m "Rel. ${{ env.TAG }}"
          git push --tags

      - uses: ncipollo/release-action@v1.10.0
        with:
          tag: golang/${{ env.TAG }}
          generateReleaseNotes: true
